import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://fragment.com/');
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Connect Telegram' }).first().click();
  const page1 = await page1Promise;
  await page.getByRole('button', { name: 'Connect Telegram' }).first().click();
  await page1.getByText('Or log in with a phone number').click();
  await page1.locator('#login-phone').click();
  await page1.locator('#login-phone-code').fill('+84');
  await page1.locator('#login-phone').fill('962836630');
  await page1.getByRole('button', { name: 'Continue' }).click();
  await page1.goto('https://oauth.telegram.org/auth/push?client_id=5444323279&origin=https%3A%2F%2Ffragment.com&return_to=https%3A%2F%2Ffragment.com%2F&scope=openid%20profile%20telegram%3Abot_access&redirect_uri=https%3A%2F%2Ffragment.com%2F&response_type=post_message');
  await page.goto('https://fragment.com/');
  await page.getByRole('button', { name: 'Connect TON' }).first().click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(1).click();
  await page.getByRole('button').nth(5).click();
  await page.getByText('Buy and Sell Usernames Secure').click();
  await page.goto('https://fragment.com/');
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.locator('#aj_content').click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.locator('#aj_content').click();
  await page.locator('#aj_content').click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.getByRole('list').getByRole('link', { name: 'My Assets' }).click();
  await page.getByRole('link', { name: 'Gifts' }).click();
  await page.getByRole('columnheader', { name: 'NFT Info' }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).click();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('heading', { name: 'My Assets' }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).click();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('heading', { name: 'My Assets' }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.locator('div').filter({ hasText: 'of 490553' }).nth(2).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('heading', { name: 'My Assets' }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.locator('div').filter({ hasText: 'of 490553' }).nth(2).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).click();
  const page2Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).nth(1).click();
  const page2 = await page2Promise;
  await page2.getByText('MainEQBtzFwH…7xc1NV_R').click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('heading', { name: 'My Assets' }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByText('Gifted by FrensGift to').click();
  const page3Promise = page.waitForEvent('popup');
  await page.locator('.tm-section-box.tm-section-bid-info > .table > tbody > tr > td:nth-child(2) > .table-cell').click();
  const page3 = await page3Promise;
  await page3.getByText('MainEQBtzFwH…7xc1NV_R').click();
  await page3.getByText('MainEQBtzFwH…7xc1NV_R').click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.locator('div').filter({ hasText: 'of 490553' }).nth(2).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('main').click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).click();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).click();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).click();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link', { name: 'Transfer to Telegram' }).click();
  await page.locator('#aj_content').click();
  await page.getByRole('link', { name: 'Move to My Account' }).click();
  await page.getByText('Move to My Account Recipient').click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.locator('#aj_content').click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.locator('#aj_content').click();
  await page.locator('#aj_content').dblclick();
  await page.getByText('Transfer to Telegram You can').click();
  await page.locator('#aj_content').click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.locator('#aj_content').click();
  await page.locator('#aj_content').click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.locator('#aj_content').click();
  await page.locator('#aj_content').click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).dblclick();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.locator('#aj_content').click();
  await page.getByRole('button', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).click();
  await page.getByRole('list').getByRole('link', { name: 'My Assets' }).click();
  await page.locator('#aj_content').click();
  await page.getByRole('link', { name: 'Gifts' }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).click();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).dblclick();
  await page.locator('div').filter({ hasText: 'Gifted by FrensGift to' }).nth(2).dblclick();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  const page4Promise = page.waitForEvent('popup');
  await page.getByRole('link', { name: 'UQBtzFwHHC_QxF6wB1Mk8Gxo ...' }).nth(1).click();
  const page4 = await page4Promise;
  await page4.getByText('MainEQBtzFwH…7xc1NV_R').click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.locator('#aj_content').click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.locator('#aj_content').click();
  await page.getByRole('main').click();
  await page.locator('#aj_content').click();
  await page.locator('#aj_content').click();
  await page.getByRole('main').click();
  await page.locator('#aj_content').click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.locator('#aj_content').click();
  await page.locator('#aj_content').click();
  await page.locator('#aj_content').click();
  await page.locator('body').press('Enter');
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('searchbox', { name: 'Search NFT by name or' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByText('Top Auctions About Terms').click();
  await page.getByText('Top Auctions About Terms').click();
  await page.getByText('Top Auctions About Terms').click();
  await page.getByRole('main').click();
  await page.getByRole('main').click();
  await page.getByRole('main').dblclick();
  await page.getByRole('main').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByText('Top Auctions About Terms').click();
  await page.getByText('Top Auctions About Terms').click();
  await page.getByText('Top Auctions About Terms').click();
  await page.getByText('Top Auctions About Terms').click();
  await page.getByText('Top Auctions About Terms').click();
  await page.getByText('Top Auctions About Terms').click();
  await page.getByText('Top Auctions About Terms').dblclick();
  await page.getByRole('link', { name: 'Vice Cream #326496 Vanilla' }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
  await page.getByRole('link').filter({ hasText: /^$/ }).click();
});